### ISSUE TITLE
SSL broken on Windows Phone 8

### ISSUE THREAD

**Issue by pascalw** [rhomobile/rhodes#217]
SSL appears to be broken on Windows Phone 8. I'm running Rhode 4.0 on a Lumia 920 and whatever HTTPS request I make I always end up getting this error:

```
Operation finished with error 35: SSL connect error
E 12/13/2013 09:02:43:320 00000f5c                  Net|   CURLNetRequest: METHOD = [GET] URL = [https://maps.googleapis.com/maps/api/geocode/json?address=weert,netherlands&sensor=false] BODY = []
E 12/13/2013 09:02:43:378 00000ff8                  SSL| SSL connection error
```

I've also tried the `verifyPeerCertificate` parameter, which would be OK during development but not in production of course, but that doesn't appear to work either.

Is there any way to work around this or is a fix available?

**Comment by priyasaini** [comment]
I am facing this same issue with android. Any solution?
Working fine on IOS though.

**Comment by alex-epifanoff** [comment]
@priyasaini what version of Rhodes are you using? please share your config files and if possible code sample/steps to reproduce.
FYI RhoMobile is now maitained by Tau Technologies http://tau-technologies.com. Community support forum for RhoMobile is now hosted at http://forums.tau-technologies.com; enterprise-grade paid support is available at tautechnologies.zendesk.com; for support options please email to info@tau-technologies.com

**Comment by priyasaini** [comment]
Thanks for your reply.

I use Rhodes 5.0.38.

Here is the rhoconfig.txt file.

# startup page for your application
start_path = '/app/User/decider_page'

# path to the options page (in this case handled by javascript)
options_path = '/app/Settings'

# location of bundle url (i.e. from rhohub.com<http://rhohub.com>); used by desktop win32 simulator
rhobundle_zip_url = ''

# optional password to access bundle (usually not required); used by desktop win32 simulator
rhobundle_zip_pwd = nil

# Rhodes log properties
# log level
# 0-trace, 1-info(app level), 2-warnings, 3-errors
# for production set to 3
MinSeverity  = 1

# enable copy log messages to standard output, useful for debugging
LogToOutput = 1

# '*' means all categories, otherwise list them : Cat1, Cat2
LogCategories = *

# what categories to exclude
ExcludeLogCategories =

# max log file size in Bytes, set 0 to unlimited size; when limit is reached, log wraps to beginning of file
MaxLogFileSize=50000000

# turn on local http server traces, off by default
net_trace = 0

# timeout of network requests in seconds (30 by default)
net_timeout = 60

# where log will be posted by RhoConf.send_log or from the log menu
# source is also open and up on http://github.com/rhomobile/rhologs, so you can deploy your own logserver
logserver = 'http://rhologs.heroku.com'

# log file prefix - contain human-readable text
logname='mustache_widget'

# Keep track of the last visited page
KeepTrackOfLastVisitedPage = 0
LastVisitedPage = ''


syncserver = 'http://172.16.18.241:9292'
Push.rhoconnect.pushServer = 'http://172.16.18.241:8675'
Push.rhoconnect.pushAppName = 'L3Ethics'

# sync server url, typically this will look like 'http://<hostname>:<port>'
# for example: 'http://localhost:9292'
#syncserver = ''
#sync_poll_interval=0

# geo location inactivity timeout (in seconds)
#geo_location_inactivity_timeout = 30

# open rhodes app in full screen mode
# default 1 for Android up to Rhodes 2.2.5.
# on all other platforms and on Android from Rhodes >2.2.5 default 0

full_screen = 0

# show top menu on Windows desktop in full screen mode (default is 0=don't show top menu)
#w32_fullscreen_menu = 1

# disable the Android page loading progress bar
disable_loading_indication = 1

# Port of the local (embedded) HTTP server. This parameter is mainly for debug purposes.
# If not specified, application will use dynamically selected one.
# WARNING!!! Remove this parameter before put application to production.
# local_server_port = 8080

# show status bar on windows mobile. default 1
#wm_show_statusbar = 1

# disable screen rotation (enabled by default) - disable possible for ANDROID and iPhone ONLY
disable_screen_rotation = 1

# disable close app when pressing back on home screen on blackberry
#bb_disable_closebyback = 0

# load images in background, this improve reaction speed on user actions, 0 by default
#bb_loadimages_async = 0

# set to 0 to reset the bulksync_state and trigger a bulk sync the next time rhodes synchronizes
#bulksync_state = 1

# hides forward button and animates back button transition
jqtouch_mode=1

splash_screen='delay=120;hcenter;hzoom;vzoom'
splash_screen='zoom'
splash_screen='none',  android = no effect
splash_screen='hzoom', android = no effect
splash_screen='vzoom', android = no effect
splash_screen='hcenter', android = no effect
splash_screen='vcenter', android = no effect

use_bb_full_browser=6



Code to fetch data (API URL is https://www.l3t.com/api/locations)
def sync_divisions
     divisionRecord = StaticPages.find(:first,:conditions => { {  :name => 'uname',   :op => '=' } => "divisionApiUrl",{
            :name => 'language',
            :op => '='
           } => Rho::RhoConfig.language,{
            :name => 'is_active',
            :op => '='
          } => '1'})
     puts "DIV RECORD::"+divisionRecord.to_s
    if divisionRecord and divisionRecord.description!=""
      #Sync from API
      puts "Sync from API"
      Rho::RhoConfig.divisionUrl = Rho::RhoSupport.url_decode(divisionRecord.description )
      re = /<("[^"]*"|'[^']*'|[^'">])*>/
              divURL =  Rho::RhoConfig.divisionUrl
              Rho::RhoConfig.divisionUrl = divURL.gsub!(re, '').strip()
              puts "DIVISION URL #{Rho::RhoConfig.divisionUrl}"
  puts "STARTING SYNC OF DIVS"
  begin
    sync_div_response = Rho::AsyncHttp.get(
    :url => Rho::RhoConfig.divisionUrl,
    :http_command => "POST",
    :headers => {"Content-Type" => "application/json"},
    :body => "",
    :verifyPeerCertificate => false)



    if sync_div_response["status"] == 'ok'
      response_data = sync_div_response["body"]
        puts "SYNC RESPOSE DATA #{response_data}"
        data = Division.find(:all)
       jsondata =  Rho::JSON.parse(response_data)
      if !data.empty?
        data.each do |dt|
          dt.destroy
        end
      end
      jsondata.each do |json|
        a = Division.create(json)
        a.name = a.title
        a.language = Rho::RhoConfig.language
        a.save
      end
    else
      puts "IMPORTANT NOTIFICATION: Error in SYNC Division API response, API response is below:"
    end
    rescue Exception => e
          puts "Error in synching Divisions, Please check log file."
          puts e.message
          puts e.backtrace.inspect
        end
      else
       puts "Seeded will be shown"
      end
  end


Any type of help is highly appreciated.

Thanks and Regards

PRIYA SAINI
Software Architect (Sr. Consultant)
106, Park Centra
Sector-30, Gurgaon
Haryana, India
Contact no: 9953590474

On 13-Jul-2017, at 2:14 am, alex-epifanoff <notifications@github.com<mailto:notifications@github.com>> wrote:


@priyasaini<https://github.com/priyasaini> what version of Rhodes are you using? please share your config files and if possible code sample/steps to reproduce.
FYI RhoMobile is now maitained by Tau Technologies http://tau-technologies.com<http://tau-technologies.com/>. Community support forum for RhoMobile is now hosted at http://forums.tau-technologies.com<http://forums.tau-technologies.com/>; enterprise-grade paid support is available at tautechnologies.zendesk.com<http://tautechnologies.zendesk.com>; for support options please email to info@tau-technologies.com<mailto:info@tau-technologies.com>

**Comment by alex-epifanoff** [comment]
@priyasaini Please use recent versions of RMS 5.5 and 6.0 released by Tau.
http://tau-technologies.com/developers/downloads/
