### ISSUE TITLE
Rho.System.getProperty('os_version') does not return the right version for Windows 8.1

### ISSUE THREAD

**Issue by ThierryW** [rhomobile/rhodes#526]
Trying to get the os version on a Windows 8.1 platform using Rho.System.getProperty('os_version') and it returns 6.2.9200 instead of 6.3.9600.

I checked my Windows version in both Registry (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion => CurrentVersion = 6.3 and Current build = 9600) and System dialog (Windows 8.1) .

FYI, I tried with a Windows 7 version and this function returns the right version, i.e. 6.1.7600.

I am using Rhodes 5.0.25.

EDIT : just tried with Rhodes 5.0.30 and this issue is still present.

Thierry

**Comment by hramovnik** [comment]
This issue is fixed for windows 10 (uwp) in this commit: https://github.com/rhomobile/rhodes/commit/a2ffafcda3f4581f909f9bb86739d47b9cfe7145 . Soon it will be merged to the main branch.
Note, that by now, Microsoft does not support win 8.x so we moved our windows mobile project to universal windows platform.
