### ISSUE TITLE
Unable to require 'bigdecimal' in Rhodes

### ISSUE THREAD

**Issue by avdhut1990** [rhomobile/rhodes#833]
Hi,

I need to use the BigDecimal library that comes along with ruby within my rhodes application. I am getting a **no such file to load --bigdecimal** error

The same works completely fine if I execute a standalone .rb file outside rhodes.

Thanks,
Avdhut

**Comment by rognar** [comment]
Hi Avdhut,

You should file a ticket at https://tautechnologies.zendesk.com

Regards,
Konstantin

**Comment by jtara** [comment]
The Ruby that you install on your computer and use to build Rhodes applications is not the same Ruby that is used by Rhodes! And so, you should not expect Rhodes to contain what is in your desktop Ruby.

The Rhodes Gem includes it's own version of Ruby. It is not a 2.x Ruby - it is actually quite old. It is used because it is what is required by the Ruby compiler used.  It also has a few libraries removed.

I believe it uses 1.9.2-p290. I keep a desktop version handy for testing out code that can be tested on desktop. (e.g. when developing a class that really has nothing to do with Rhodes.) By using 1.9.2-p290 I can be reasonably assured it will work the same in Rhodes. (unless it uses missing libraries).
