### ISSUE TITLE
AndroidOpenSSL libraries out of date

### ISSUE THREAD

**Issue by edgarelc** [rhomobile/rhodes#839]
Hello guys,

I need to use OpenSSL in my app and the Google Play Store is rejecting it because it's using an unsecure (older) version. They are asking to update to at least version 1.01r. I tried to use the files in this branch but there's reference to older versions of OpenSSL in the apk (https://github.com/louisatome/rhodes/tree/master/lib/extensions/openssl.so/ext/android).

Is there any chance you can help here by compile those extensions using a newer version of OpenSSL?

Thanks!

**Comment by alex-epifanoff** [comment]
Hi Edgar,

We actually have built recent openSSL 1.1.0 and it is avalilable in 'rho-tau-extensions': 'openssl-edge' and 'openssl.so-edge'. We have reports there were some issues, probably related to outdated Ruby VM, but we know that apps were successfully published to play store with this.
You can get extensions gem from our site:
http://rhomobile.tau-technologies.com/5.5/5.5.0.11/rho-tau-extensions-5.5.0.11.gem

Change your build.yml to use 'edge' versions of openssl and openssl.so extensions.

Regards,
Alex.

**Comment by edgarelc** [comment]
Thanks Alex! That's great info. This effectively adds openSSL 1.1.0 but I have another third party library that doesn't like it. I tried updating that library but it requires a higher version of ruby compare to the one I'm using. I've taken this out of my project for now and I'll re-start it as an upgrade project later. You guys rock! :)

**Comment by louisatome** [comment]
Hello @edgarelc ,

I had the same issue for android and i recompiled a newer version of OpenSSL (1.0.1u) that is allowed by Google Store. You can find it in my fork : https://github.com/louisatome/rhodes/tree/5-5-stable/lib/extensions/openssl.so . 
I'm not 100% sure that my OpenSSL build is OK because the size of the binary is far smaller than the current one (14 MB => 4MB) but it works well in my project.
