### ISSUE TITLE
Error on iOS 10.2 when downlaodFile

### ISSUE THREAD

**Issue by ThomasAtome** [rhomobile/rhodes#841]
Hi,

I have so mistakes when I used the Rho::Network.downloadFile().

I have two devices on iOS 9 and one on 10.2.

The two devices on the sdk 9 work well, file download, but the 10.2 don't want to download the file and the callback give me error_code 1.

I don't have more informations.. The picture which i try to download => [http://images.digopaul.com/wp-content/uploads/related_images/2015/09/08/gh_1.jpg](url)

Thanks

**Comment by dmitrys** [comment]
On iOS 10 you should specify http domains.
Add this to iphone section of build.yml :

iphone:
  http_connection_domains: ['images.digopaul.com']

this supported from 5.5.0.4 stable - current stable version is 5.5.0.12

Also you can manually modify your Info.plist and define next property :

<key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>

Be sure - you removed NSAllowsArbitraryLoadsInWebContent enabled by default.
In current Master version we change this functioanlity - now we removed NSAppTransportSecurity from default project and developers should setup it by self in build.yml with new Info.plist modify keys. It will be included into next developers version(5.5.10) soon.

**Comment by ThomasAtome** [comment]
Hi,

I try to remove manually the NSAllowsArbitraryLoadsInWebContent key, and all works fine.

But.. the problem now is that i can't patch it or remove it for every build. The key is added automatically when i clean my project and build it.

I try, with the last stable version 5.5.0.12, to not assign it in the build.yml, but the key is generated again.. And if i set it to false, i can' t download the image.

So, do you have any solution or workaround for delete this key ? Or why the key is generated automatically ?

Thanks

**Comment by dmitrys** [comment]
Master branch : 
Now we completely remove automatic manipulation with NSAppTransportSecurity because Apple deeply checking applications with this key.
Now developer should enable this key by self. We added new keys in build.yml for direct modifying of Inof.plist content. So for add just NSAllowsArbitraryLoads developer should add this to build.yml :

iphone:
  info_plist_data:
    NSAppTransportSecurity:
      NSAllowsArbitraryLoads: true

Stable branch:
We can not not make the same change in stable, so we just remove enable of NSAllowsArbitraryLoadsInWebContent. I think it is solve your issue.
You can download 5.5.0.17 from this :
https://drive.google.com/drive/folders/0B-a6sKAdb8jDY2JSeTVYclBmSDQ?usp=sharing
